[workspace]
resolver = "2"
members = ["lib", "playback", "server", "tui"]

[workspace.package]
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Terminal Music and Podcast Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a/flac/wav/ogg vorbis files."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui", "music", "youtube", "podcast"]
categories = [
    "command-line-interface",
    "command-line-utilities",
    "multimedia::audio",
]
readme = "./README.md"
version = "0.9.1"
rust-version = "1.77"

[workspace.dependencies]
# "version" key is required, as per https://github.com/rust-lang/cargo/issues/11133
termusic-lib = { path = "lib/", version = "0.9.1" }
# need to disable "default-features" here for "termusic-server", otherwise the "default-features" in "termusic-server" have no effect
termusic-playback = { path = "playback/", version = "0.9.1", default-features = false }
ahash = "^0.8"
anyhow = { version = "1.0", features = ["backtrace"] }
async-channel = "2.2"
async-trait = "0.1"
base64 = "0.22"
bytes = "1.6"
chrono = "^0.4.23"
clap = { version = "4.5", features = ["derive", "env"] }
cpal = "^0.15"
ctrlc = { version = "3.4", features = ["termination"] }
dirs = "5.0"
discord-rich-presence = { version = "0.2" }
escaper = "0.1.1"
figment = { version = "0.10", features = ["toml"] }
glib = { version = "0.20" }
gstreamer = { version = "0.23" }
hex = "0.4"
id3 = "1.13"
# image cannot be upgraded to 0.25 because of viuer, see https://github.com/atanunq/viuer/issues/56
image = "0.24"
include_dir = "0.7"
lazy_static = "1.4"
libaes = "0.7"
libmpv2 = "4"
# lofty = "0.21"
lofty = { git = "https://github.com/Serial-ATA/lofty-rs.git" }
log = "0.4"
flexi_logger = "0.28"
colored = "2.0"
md5 = "0.7"
num-bigint = "0.4"
opml = "1.1"
parking_lot = "^0.12"
pathdiff = { version = "0.2", features = ["camino"] }
percent-encoding = "2.2"
pinyin = "0.10"
pretty_assertions = "1.4"
quick-xml = "0.36"
rand = "0.8"
regex = "^1.5.5"
reqwest = { version = "0.12", features = [
    "cookies",
    "gzip",
    "json",
    "stream",
] }
rfc822_sanitizer = "0.3"
rss = "2.0"
rusqlite = { version = "0.32", features = ["bundled"] }
sanitize-filename = "0.5"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
shellexpand = { version = "3.1", features = ["path"] }
soundtouch = "0.4.2"
souvlaki = { version = "0.7.3", default-features=false, features = ["use_zbus"] }
stream-download = { version = "0.9", features = ["reqwest-rustls"] }
symphonia = { version = "0.5.1", features = [
    "default",
    "aac",
    "mp3",
    "isomp4",
    "alac",
    "flac",
    "mkv",
] }
sysinfo = { version = "^0.31", default-features = false, features = ["system"] }
tempfile = "3.10"
textwrap = "0.16"
tokio = { version = "1.37", features = ["sync", "macros", "rt","rt-multi-thread"] }
tokio-util = "0.7"
toml = "0.8"
# only update prost and tonic major versions together
prost = "0.13"
tonic = "0.12"
tonic-build = "0.12"
tuirealm = { version = "~1.8", features = ["serialize"] }
tui-realm-stdlib = "~1.2"
tui-realm-treeview = "~1.1"
unicode-segmentation = "1.10"
unicode-width = "^0.1.8"
urlencoding = "2.1"
viuer = "0.7"
walkdir = "2.5"
wildmatch = "2.3"
ytd-rs = { version = "0.1", features = ["yt-dlp"] }
futures = "0.3"
# transistive dependency for some packages (like libsqlite), manually specified to upgrade the version, see https://github.com/rusqlite/rusqlite/issues/1543
cc = "1.1"

[profile.release]
# lto = true
# panic = 'abort'
# opt-level = 'z'
# codegen-units = 1
