[workspace]
resolver = "2"
members = ["lib", "playback", "server", "stream", "tui"]

[workspace.package]
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Terminal Music and Podcast Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a/flac/wav/ogg vorbis files."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui", "music", "youtube", "podcast"]
categories = [
    "command-line-interface",
    "command-line-utilities",
    "multimedia::audio",
]
readme = "./README.md"
version = "0.7.11"
rust-version = "1.70"

[workspace.dependencies]
termusic-lib = { path = "lib/", version = "0.7.11" }
termusic-playback = { path = "playback/", version = "0.7.11" }
termusic-stream = { path = "stream/", version = "0.7.11" }
ahash = "^0.8"
anyhow = { version = "1.0", features = ["backtrace"] }
async-trait = "0.1"
base64 = "0.21"
bytes = "1"
chrono = "^0.4.23"
clap = { version = "4", features = ["derive", "env"] }
cpal = "^0.15"
ctrlc = { version = "3", features = ["termination"] }
dirs = "5.0"
discord-rich-presence = { version = "0.2" }
escaper = "0.1.1"
figment = { version = "0.10", features = ["toml"] }
futures = "0.3"
futures-util = "0.3"
glib = { version = "0.18" }
gstreamer = { version = "0.21" }
hex = "0.4"
id3 = "1"
image = "0.24"
include_dir = "0.7"
lazy_static = "1.4"
libaes = "0.7"
libmpv-sys = { version = "3" }
lofty = "0.18"
log = "0.4"
flexi_logger = "0.27"
colored = "2.0"
md5 = "0.7"
num-bigint = "0.4"
opml = "1"
parking_lot = "^0.12"
pathdiff = { version = "0.2", features = ["camino"] }
percent-encoding = "2.2"
pinyin = "0.10"
pretty_assertions = "1"
prost = "0.12"
quick-xml = "0.31"
rand = "0.8"
rangemap = "1"
regex = "^1.5.5"
reqwest = { version = "0.11", features = [
    "blocking",
    "cookies",
    "gzip",
    "json",
    "stream",
] }
rfc822_sanitizer = "0.3"
rss = "2"
rusqlite = { version = "0.30", features = ["bundled"] }
sanitize-filename = "0.5"
semver = "^1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3"
souvlaki = "0.7.2"
symphonia = { version = "0.5.1", features = [
    "default",
    "aac",
    "mp3",
    "isomp4",
    "alac",
    "flac",
    "mkv",
] }
sysinfo = "^0.30"
tap = "1"
tempfile = "3"
textwrap = "0.16"
tokio = { version = "1", features = ["sync", "macros", "rt"] }
# tokio-stream = "*"
toml = "0.8"
hyper = "0.14.26" # keep this in-sync with tonic's requirement
tonic = "0.10"
tonic-build = "0.10"
tracing = "0.1"
tuirealm = { version = "~1.8", features = ["serialize"] }
tui-realm-stdlib = "1.2"
tui-realm-treeview = "1.1"
unicode-segmentation = "1.10"
unicode-width = "^0.1.8"
urlencoding = "2"
# viuer = { version = "0.6", features = ["sixel"] }
viuer = "0.7"
walkdir = "2"
wildmatch = "2"
yaml-rust = "^0.4.5"
ytd-rs = { version = "0.1", features = ["yt-dlp"] }
async-channel = "2"


[profile.release]
# lto = true
# panic = 'abort'
# opt-level = 'z'
# codegen-units = 1
